<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="skodarapid.lan" failures="1" tests="4" name="Buggy Cars Login Tests" time="4.901" errors="0" timestamp="2022-07-08T10:46:33 NZST">
  <testcase classname="com.buggy.car.portals.tests.LoginTest" name="test_blank_username" time="0.294"/>
  <testcase classname="com.buggy.car.portals.tests.LoginTest" name="test_invalid_password" time="0.579"/>
  <testcase classname="com.buggy.car.portals.tests.LoginTest" name="test_invalid_username" time="0.256"/>
  <testcase classname="com.buggy.car.portals.tests.LoginTest" name="test_valid_login" time="1.128">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Buggy Cars] but found [Buggy Cars Rating],
	expected [Buggy Cars Portal] but found [Buggy Cars Rating]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Buggy Cars] but found [Buggy Cars Rating],
expected [Buggy Cars Portal] but found [Buggy Cars Rating]
at com.buggy.car.portals.tests.LoginTest.test_valid_login(LoginTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_valid_login -->
</testsuite> <!-- Buggy Cars Login Tests -->
